<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kolom pembagi: continent, kingdom, district, cluster, dll.
        $categories = [
            ['cluster' => 'products', 'parent_id' => null, 'parent_slug' => null, 'division' => null, 'varian' => null, 'name' => 'Jewelry', 'nama' => 'Perhiasan', 'slug' => 'jewelry', 'description' => null, 'has_children' => true],
            ['cluster' => 'products', 'parent_id' => null, 'parent_slug' => null, 'division' => null, 'varian' => null, 'name' => 'Bullions', 'nama' => 'LM', 'slug' => 'bullions', 'description' => null, 'has_children' => true],
            ['cluster' => 'products', 'parent_id' => 1, 'parent_slug' => 'jewelry', 'division' => 'material', 'varian' => 'gold', 'name' => 'Gold Jewelry', 'nama' => 'Perhiasan Emas', 'slug' => 'gold-jewelry', 'description' => null, 'has_children' => false],
            ['cluster' => 'products', 'parent_id' => 1, 'parent_slug' => 'jewelry', 'division' => 'material', 'varian' => 'silver', 'name' => 'Silver Jewelry','nama' => 'Perhiasan Perak', 'slug' => 'silver-jewelry', 'description' => null, 'has_children' => false],
            ['cluster' => 'products', 'parent_id' => 2, 'parent_slug' => 'bullions', 'division' => 'material', 'varian' => 'gold','name' => 'Gold Bullions', 'nama' => 'LM Emas', 'slug' => 'gold-bullions', 'description' => null, 'has_children' => false],
            ['cluster' => 'products','parent_id' => 2, 'parent_slug' => 'bullions', 'division' => 'material', 'varian' => 'silver', 'name' => 'Silver Bullions', 'nama' => 'LM Perak', 'slug' => 'silver-bullions', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Earring', 'nama' => 'Anting', 'slug' => 'earring', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Ear Stud', 'nama' => 'Giwang', 'slug' => 'ear-stud', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Ring', 'nama' => 'Cincin', 'slug' => 'ring', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Necklace', 'nama' => 'Kalung', 'slug' => 'necklace', 'description' => null, 'has_children' => true],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Bracelet', 'nama' => 'Gelang Tangan', 'slug' => 'bracelet', 'description' => null, 'has_children' => true],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Anklet', 'nama' => 'Gelang Kaki', 'slug' => 'anklet', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Pendant', 'nama' => 'Liontin', 'slug' => 'pendant', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => null, 'parent_slug' => null, 'division' => 'ornament_types', 'varian' => null, 'name' => 'Brooch', 'nama' => 'Bros', 'slug' => 'brooch', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_types', 'varian' => null, 'name' => 'Choker', 'nama' => 'Kalung Choker', 'slug' => 'choker', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => 11, 'parent_slug' => 'bracelet', 'division' => 'ornament_types', 'varian' => null, 'name' => 'Chain Bracelet', 'nama' => 'Gelang Tangan Rantai', 'slug' => 'chain-bracelet', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => 11, 'parent_slug' => 'bracelet', 'division' => 'ornament_types', 'varian' => null, 'name' => 'Round Bracelet', 'nama' => 'Gelang Tangan Bulat', 'slug' => 'round-bracelet', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => 12, 'parent_slug' => 'anklet', 'division' => 'ornament_types', 'varian' => null, 'name' => 'Chain Anklet', 'nama' => 'Gelang Kaki Rantai', 'slug' => 'chain-anklet', 'description' => null, 'has_children' => false],
            ['cluster' => 'jewelry', 'parent_id' => 12, 'parent_slug' => 'anklet', 'division' => 'ornament_types', 'varian' => null, 'name' => 'Round Anklet', 'nama' => 'Gelang Kaki Bulat', 'slug' => 'round-anklet', 'description' => null, 'has_children' => false],
            // Anting
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Desi', 'slug' => 'anting-desi'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Desi Polos', 'slug' => 'anting-desi-polos'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Jepit', 'slug' => 'anting-jepit'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Jepit Ukir', 'slug' => 'anting-jepit-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gipsi', 'slug' => 'anting-gipsi'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gipsi Ukir', 'slug' => 'anting-gipsi-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kait', 'slug' => 'anting-kait'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kait Panjang', 'slug' => 'anting-kait-panjang'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kenip', 'slug' => 'anting-kenip'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Toge', 'slug' => 'anting-toge'],
            ['cluster' => 'jewelry', 'parent_id' => 7, 'parent_slug' => 'earring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tusuk Sate', 'slug' => 'anting-tusuk-sate'],
            // Giwang
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => '1/2 Tribal', 'slug' => 'giwang-1/2-tribal'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kotak', 'slug' => 'giwang-kotak'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Mata Burung', 'slug' => 'giwang-mata-burung'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Mata Desi', 'slug' => 'giwang-mata-desi'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Panjang', 'slug' => 'giwang-panjang'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Pentol Polos', 'slug' => 'giwang-pentol-polos'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Pentol Ukir', 'slug' => 'giwang-pentol-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Segitiga', 'slug' => 'giwang-segitiga'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tribal', 'slug' => 'giwang-tribal'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tribal Pasir', 'slug' => 'giwang-tribal-pasir'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tribal Ukir', 'slug' => 'giwang-tribal-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Fashion', 'slug' => 'giwang-fashion'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Bintang', 'slug' => 'giwang-bintang'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Chanel', 'slug' => 'giwang-chanel'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Hello Kitty', 'slug' => 'giwang-hello-kitty'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kembang', 'slug' => 'giwang-kembang'],
            ['cluster' => 'jewelry', 'parent_id' => 8, 'parent_slug' => 'ear-stud', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Kembang Polos', 'slug' => 'giwang-kembang-polos'],
            // Cincin
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => '1/2 Rantai', 'slug' => 'cincin-1/2-rantai'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => '1/2 Pasir', 'slug' => 'cincin-1/2-pasir'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Bambu Ukir', 'slug' => 'cincin-bambu-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Dubai', 'slug' => 'cincin-dubai'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Listring Aurel', 'slug' => 'cincin-listring-aurel'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Listring V', 'slug' => 'cincin-listring-v'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Ring Patkok', 'slug' => 'cincin-patkok'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Ring Polos', 'slug' => 'cincin-ring-polos'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Stempel', 'slug' => 'cincin-stempel'],
            ['cluster' => 'jewelry', 'parent_id' => 9, 'parent_slug' => 'ring', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Wedding', 'slug' => 'cincin-wedding'],
            // Kalung
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Aurel', 'slug' => 'kalung-aurel'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Balok Mini', 'slug' => 'kalung-balok-mini'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Cabai', 'slug' => 'kalung-biji-cabai'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Lada', 'slug' => 'kalung-biji-lada'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Padi', 'slug' => 'kalung-biji-padi'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Timun', 'slug' => 'kalung-biji-timun'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Timun Lilit', 'slug' => 'kalung-biji-timun-lilit'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Boston', 'slug' => 'kalung-boston'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Cassandra', 'slug' => 'kalung-cassandra'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Cassandra Ukir', 'slug' => 'kalung-cassandra-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gepeng', 'slug' => 'kalung-gepeng'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Holo', 'slug' => 'kalung-holo'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Holo Safir', 'slug' => 'kalung-holo-safir'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Holo Ukir', 'slug' => 'kalung-holo-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Italy', 'slug' => 'kalung-italy'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Italy Kaca', 'slug' => 'kalung-italy-kaca'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Italy Santa', 'slug' => 'kalung-italy-santa'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Milano Bulat', 'slug' => 'kalung-milano-bulat'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Milano Gepeng', 'slug' => 'kalung-milano-gepeng'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Milano Kotak', 'slug' => 'kalung-milano-kotak'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Miyata', 'slug' => 'kalung-miyata'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Nori', 'slug' => 'kalung-nori'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Nori Balok', 'slug' => 'kalung-nori-balok'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Nori Balok Ukir', 'slug' => 'kalung-nori-balok-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Plexi', 'slug' => 'kalung-plexi'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Rantai Gepeng', 'slug' => 'kalung-rantai-gepeng'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Santa', 'slug' => 'kalung-santa'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Lovina', 'slug' => 'kalung-lovina'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Sela Seli', 'slug' => 'kalung-sela-seli'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Silinder', 'slug' => 'kalung-silinder'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tambang Lilit', 'slug' => 'kalung-tambang-lilit'],
            ['cluster' => 'jewelry', 'parent_id' => 10, 'parent_slug' => 'necklace', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Tambang Variasi', 'slug' => 'kalung-tambang-variasi'],
            // Gelang Tangan Rantai
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Biji Lada Kombinasi', 'slug' => 'gelang-tangan-rantai-biji-lada-kombinasi'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Cor', 'slug' => 'gelang-tangan-rantai-cor'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gepeng', 'slug' => 'gelang-tangan-rantai-gepeng'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Hollow', 'slug' => 'gelang-tangan-rantai-hollow'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Hollow Kombinasi', 'slug' => 'gelang-tangan-rantai-hollow-kombinasi'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Hollow Ukir', 'slug' => 'gelang-tangan-rantai-hollow-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Hollow Safir', 'slug' => 'gelang-tangan-rantai-hollow-safir'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Serut', 'slug' => 'gelang-tangan-rantai-serut'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Sisik Naga', 'slug' => 'gelang-tangan-rantai-sisik-naga'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Sisik Naga Double', 'slug' => 'gelang-tangan-rantai-sisik-naga-double'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Susun Sirih', 'slug' => 'gelang-tangan-rantai-susun-sirih'],
            ['cluster' => 'jewelry', 'parent_id' => 16, 'parent_slug' => 'chain-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Wedding', 'slug' => 'gelang-tangan-rantai-wedding'],
            // Gelang Tangan Bulat
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Polos', 'slug' => 'gelang-tangan-bulat-polos'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Ukir', 'slug' => 'gelang-tangan-bulat-ukir'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Cartier', 'slug' => 'gelang-tangan-bulat-cartier'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Fashion', 'slug' => 'gelang-tangan-bulat-fashion'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gelombang', 'slug' => 'gelang-tangan-bulat-gelombang'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Keroncong', 'slug' => 'gelang-tangan-bulat-keroncong'],
            ['cluster' => 'jewelry', 'parent_id' => 17, 'parent_slug' => 'round-bracelet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Ular', 'slug' => 'gelang-tangan-bulat-ular'],
            // Gelang Kaki
            ['cluster' => 'jewelry', 'parent_id' => 18, 'parent_slug' => 'chain-anklet', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gelang Kaki Rantai', 'slug' => 'gelang-kaki-rantai'],
            // Liontin
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Batu', 'slug' => 'liontin-batu'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Chanel', 'slug' => 'liontin-chanel'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Desi', 'slug' => 'liontin-desi'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Dubai Ukir Pohon Kelapa', 'slug' => 'liontin-dubai-ukir-pohon-kelapa'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Gucci', 'slug' => 'liontin-gucci'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Huruf', 'slug' => 'liontin-huruf'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Louis Vuitton', 'slug' => 'liontin-louis-vuitton'],
            ['cluster' => 'jewelry', 'parent_id' => 13, 'parent_slug' => 'pendant', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Salib', 'slug' => 'liontin-salib'],
            // Bros
            ['cluster' => 'jewelry', 'parent_id' => 14, 'parent_slug' => 'brooch', 'division' => 'ornament_varians', 'varian' => null, 'decription' => null, 'has_children' => false, 'nama' => null, 'name' => 'Bros Cantik', 'slug' => 'brooch-bros-cantik'],
        ];

        // foreach ($categories as $category) {
        //     \App\Models\ProductCategory::create($category);
        // }
        DB::table('categories')->insert($categories);
    }
}
